version: "3.9"
services:
  api:
    build:
      context: ./movie-review-backend
      dockerfile: Dockerfile
    environment:
      - PORT=5000
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "5000:5000"
    restart: unless-stopped
